### PR TITLE
Updated version of Product Vision and first draft of Product Planning

### PR DESCRIPTION
**Pull request by BjornvdLaan**

### CODE REVIEW

**Comment by mvandorp** [comment]
The title of section 5.1 of ProductPlanning.pdf is Dutch whereas the rest of the document is written in English.

**Comment by adamIqbal** [comment]
not merged and closed, as final version was commited.

**Comment by mvandorp** [comment]
Hi friend! 

Just  take a look at that amazing and wonderful stuff, you're going to love it for  sure!  More info  here  http://possible.indraniboyle.com/e5lgo

Pardon my monkey thumbs, martijnvandorp

47292

**Comment by mvandorp** [comment]
Greetings, 
I  suddely came accross this stuff, this  is just  genious, take a look http://ltakechocu.thecoffeescholar.com/e5pglk
Yours truly, martijnvandorp

**Comment by mvandorp** [comment]
Hello friend, 

I've got that nice stuff for you, it is awesome. Just take a look  at it http://ltirdithihu.plbudget.com/e5vodb

Best Wishes, martijnvandorp

**Comment by mvandorp** [comment]
Dear, 

I know you were looking  for that stuff  for   a long time, so  I guess I found  it,  take a look  here http://nkasukache.rusticcreekresort.com/e2owveb

Best regards, martijnvandorp

**Comment by mvandorp** [comment]
Dear friend! 

I've decided  to  spend a  couple of days  in camping, just take a look  at that  place http://jumolythy.midget-stripper.com/e2bvsv

Best wishes, martijnvandorp

**Pull request closed without merging**
