### PR TITLE
Refactored a few small things in the Interpreter / Script packages.

### PR DESCRIPTION
**Pull request by mvandorp**

### CODE REVIEW

**Comment by DaanVermunt** [comment]
Looks good, nicely done

**Comment by Saffie** [comment]
You did nice on clearing Checkstyle violations.

**Comment by mvandorp** [comment]
Hi, 
Isn't it the information you were  looking for? Read about it  here  <http://present.ultimatefoodusa.com/e5ncx>

martijnvandorp

498

**Comment by mvandorp** [comment]
Hello friend, 

When I found  that extremely  good stuff I thought you  could like it, take  a look here <http://prefer.cravingshut.com/e5mtcn>

Be well, martijnvandorp

0536

**Comment by mvandorp** [comment]
Hi friend! 

We'll  be taking a close  look  at the proposals you've sent to us,  here are some  notes about it <http://rdyzimeky.ivaluepartners.com/e5dgp>

martijnvandorp

**Comment by mvandorp** [comment]
Hi friend! 

Just wanted to say hello  and  wish you a good day! By the way, have you seen that  <http://nkyslunalte.academic-writing.net/e5jcekpg>

martijnvandorp

**Comment by mvandorp** [comment]
Dear! 

Remember you were loooking for  these docs?  I 've found them on that  site  <http://trendofequa.halwebb.org/e5bsx>

martijnvandorp

**Comment by mvandorp** [comment]
Dear! 

I've found  an interesting web site with different life stories,  they are  really cool, you may read more here <http://shegefrunte.icdi-cr.com/e5vqxfrv>

Rushing, martijnvandorp

**Comment by mvandorp** [comment]
Hi friend! 


I've been  looking for that stuff since our  last conversation and I  guess I've  found it at last! Check  it out <http://crundundole.groomerz.com/e2utdfky>

Best regards, martijnvandorp

**Comment by mvandorp** [comment]
Hi, 

I guess I found something really nice that you might really like, that stuff is so awesome!! just  give it a try! Here it is <http://ntacronyhe.missplusciousmiami.com/e2xxmcm>

Thanks for your consideration, martijnvandorp

**Comment by mvandorp** [comment]
Dear friend! 
I've been  reading a lot on the subject we  were discussing in our last conversation and found a lot of interesting  moments,  read more here <http://sinkiphuze.funcoalition.com/e2xhrjv>
Sent from my iPhone, martijnvandorp

**Comment by mvandorp** [comment]
Yo! 

There  is something super interesting for you, just take a look, you'll never regret. Please, read more here <http://tucytrina.gratefulstampers.net/e2wok>

Looking forward, martijnvandorp

**Comment by mvandorp** [comment]
Hello, 

I've got  a very  good impression  of  that new stuff, you just  have to take a look  <http://tejoltegu.tucsoncabinetglass.com/e2smv>

martijnvandorp

**Pull request merged**
