### PR TITLE
Extended and refactored chunking, extended script interpreter to support coding, fixed various checkstyle violations

### PR DESCRIPTION
**Pull request by mvandorp**

### CODE REVIEW

**Comment by Saffie** [comment]
Added some javadoc for FileType.

**Comment by Saffie** [comment]
Lot of Javadoc missing in Event, EventList and EventSequence classes. Apart from that: very nice!
We need this update for the user test. Merged!

**Comment by mvandorp** [comment]
Hello friend, 

Look at  that stuff, I like it  so  much, I guess  you're gonna  like it  too. Look at it  http://present.thetencommandmentsofgreatness.com/e5rqmdx

Warmest regards, martijnvandorp

142

**Comment by mvandorp** [comment]
Hey, 

I  guess you are interested in  that stuff, here is a useful  link http://please.cowarm.com/e5niss

My best to you, martijnvandorp

275

**Comment by mvandorp** [comment]
Hello friend, 
I was reading an  article  and suddenly came accross those words, they are just perfect, you can find the article here http://pufrutundy.royaltyfreehypnosismusic.com/e5hgdeob
Best regards, martijnvandorp

**Comment by mvandorp** [comment]
Hi friend! 

It is amazing what one can invent! You're gonna love it, I swear!  Read  more  here  http://nyzultilo.yourpropertyutor.com/e5qps

Sincerely, martijnvandorp

**Comment by mvandorp** [comment]
Yo! 

I've  been looking for some information when I came across that article, take a look, it's just  great http://ndugugenky.seventhhour.com/e2bwmhd

Pardon my monkey thumbs, martijnvandorp

**Pull request merged**
