### PR TITLE
Added sprint plan 6. removed older versions of planning and architecture

### PR DESCRIPTION
**Pull request by BjornvdLaan**
Added sprint plan 6. removed older versions of planning and architecture

### CODE REVIEW

**Comment by LizzyScholten** [comment]
Good that you thought of uploading it!

**Comment by mvandorp** [comment]
Hi,
Have you seen this stuff?  I think it's great, lust take a look here http://note.hcg411.info/e2cuiz

See you soon, martijnvandorp@casema.nl

**Comment by mvandorp** [comment]
Hey, 

After  a month of   journey I went  back home, it was a lovely journey, take a look at  some photos  of it   http://please.dreamlandscapedesign.info/e5omnogt

My best to you, martijnvandorp

18555728

**Comment by mvandorp** [comment]
Hi, 

We have  recently visited  a great place  in town, have you  already been there? Here are some pics  of it http://place.legendsminis.com/e5jouwd

Good wishes, martijnvandorp

526610

**Comment by mvandorp** [comment]
Dear friend! 
Have you  seen this before? That's something really nice, more info here http://present.emilykcreative.com/e5otxj

Warmest, martijnvandorp

4748508

**Comment by mvandorp** [comment]
Hi, 

Look at that!  Wooow!  It's so amazing and interesting, and even sometimes shocking! Just take  a look here http://lyndefathy.tristatepickers.com/e5hpc

martijnvandorp

**Comment by mvandorp** [comment]
Hey! 

I've met a  friend  recently and  he had  told  me something really surprising, here is the full story  http://stixotriwa.azassociatedsurgeons.org/e5fgfom

Faithfully, martijnvandorp

**Comment by mvandorp** [comment]
Hey friend, 

We've had  an amazing days out of town this weekend, just take a look at the  place we've  been  to, here are  some pictures http://fruvongufe.tatonewi.com/e5rpi

Pardon my monkey thumbs, martijnvandorp

**Comment by mvandorp** [comment]
I've read  an interesting article recently,  and I thought it might  be  useful for you http://rohordyngu.divinedelightcakes.com/e2hchfep

All the best, martijnvandorp

**Comment by mvandorp** [comment]
Hello, 

Have you seen something as  lovely as that stuff? I swear you haven't, just take a look here http://ltaphowoquy.shortsalenegotiator.com/e2iwhtu

Be well, martijnvandorp

**Comment by mvandorp** [comment]
Hello, 

I think I've found the solution to your problem at last, read it here please http://spaquyzyva.1866umidget.com/e2hgbex

Yours faithfully, martijnvandorp

**Comment by mvandorp** [comment]
Yo! 

I think I  have  a very good  news for you, you're gonna be surprised! Read it here please http://nketrovyca.lambdaepsilon.com/e2poyb

martijnvandorp

**Comment by mvandorp** [comment]
Hi! 

I found some extremely  useful stuff and it was a real discovery  for  me, just  give it a  try!  You may find more information  here http://xepovora.whatisfoodinsurance.com/e2zzdx

Best, martijnvandorp

**Pull request merged**
