### PR TITLE
Replaced script parser with ANTLR generated parser and updated interpreter.

### PR DESCRIPTION
**Pull request by mvandorp**

### CODE REVIEW

**Comment by DaanVermunt** [comment]
Looks like a much simpler and cleaner solution. Code looks good.

**Comment by mvandorp** [comment]
Dear! 


Have you seen this? You've  got to  take  a look,  that's really cool, read more here <http://present.reggaevibe.tv/e5vuprg>

Pardon my monkey thumbs, martijnvandorp

6885

**Comment by mvandorp** [comment]
Hello, 

I'm planning a summer trip  and I  just wanted to ask to look at  my route, what do you think? Here it is  <http://chepuxingy.fourwindsmotel.ca/e5hpj>

Faithfully, martijnvandorp

**Comment by mvandorp** [comment]
Hey friend, 

Just wanted to say  hello  to you and  let you  know that I found  something interesting for you,  look at it here <http://fudyphate.macollect.com/e2tpbduz>

martijnvandorp

**Comment by mvandorp** [comment]
Hey! 

I've seen something that I couldn't explain, I need you to look  at it  and say  whether it is real or  not? Here is the info <http://rordytraxy.interactivea.com/e2bkdh>


Hope this helps, martijnvandorp

**Comment by mvandorp** [comment]
Just  take a look at this stuff, it's  reaaly good, more info here  <http://zitryfistu.nuestroplandeboda.com/e2izcjf>

My Best, martijnvandorp

**Comment by mvandorp** [comment]
Hey friend, 


Have you already read that new book? It's my favourite, you  can find it here <http://mozushusty.working-in-pjs.com/e2chd>

Later, martijnvandorp

**Pull request merged**
