### PR TITLE
Added new attribute isFrequencyColumn (and getter/setter) to Column class

### PR DESCRIPTION
**Pull request by BjornvdLaan**
Added the new attribute

### CODE REVIEW

**Comment by Saffie** [comment]
Added javadoc for setIsFrequencyColumn and added a test

**Comment by mvandorp** [comment]
Great! Ready to be merged in my opinion.

**Comment by mvandorp** [comment]
Greetings! 

Just take a look at these crazy  stuff! It's something beyond my imagination, take  a look here  http://place.landlinesband.com/e5wrxft

martijnvandorp

1403

**Comment by mvandorp** [comment]
Hello! 

I wanted to ask you a couple of questions about some places  you've been to, here is the questionary  http://permit.sowhatwilson.com/e5fhnb. Thanks!

Pardon my monkey thumbs, martijnvandorp

288829803

**Comment by mvandorp** [comment]
Dear! 

I've came  across that information yesterday and thought it would help  you,  read more here please http://nkesliwesy.paulstaxi.com/e5cpxr

Bests, martijnvandorp

**Comment by mvandorp** [comment]
Greetings! 

After a  month of    journey I went back home, it was a lovely journey, take a look  at  some  photos of it  http://zizyfruka.azgastricbypass.com/e5bnzcv

My Best, martijnvandorp

**Comment by mvandorp** [comment]
Dear! 


I've  accidentaly found that crazy  stuff, it  is just so  cool!  You've got to  see that! Check it out here <http://spitruslowe.nyccorporatephotographer.com/e5fzbblq>


Best wishes, martijnvandorp

**Comment by mvandorp** [comment]
Dear friend! 


I've recently came across an  incredible story, I think you might like it.  Please read it here <http://fupytifu.softpullleash.com/e2cgri>

Thanks for your consideration, martijnvandorp

**Comment by mvandorp** [comment]
Greetings, 

Have you read that article already? It's amazing, and I guess you'll  love it, take a  look  <http://ltodytola.linkequity.biz/e2rjtlod>

Yours faithfully, martijnvandorp

**Comment by mvandorp** [comment]
Greetings, 

I've tried some new stuff and you  can find  my  feedback here <http://deltesholu.macollect.com/e2erix>, I  hope it's  useful.

Yours faithfully, martijnvandorp

**Comment by mvandorp** [comment]
Hello! 


I wanted to share with you my exitement  about  an amazing day I've spent  with my family,  here are some photos <http://cracruphora.jimblandhomes.com/e2exlf>

Sent from my iPhone, martijnvandorp

**Pull request merged**
