### PR TITLE
Test operations constrained tested

### PR DESCRIPTION
**Pull request by adamIqbal**
Could be extended, didnt look like there was need for exhtausive testing of predicate function.

### CODE REVIEW

**Comment by adamIqbal** [comment]
almost forgot, 90,6% coverage, didnt test the private empty constructor, as I could have accessed it through reflection, but testing an empty java constructor felt like waste of my time.

**Comment by adamIqbal** [comment]
extended connect a bit, not too much was already reasonably high coverage.

**Comment by adamIqbal** [comment]
test table_with_days, 96,6% coverage.

**Comment by DaanVermunt** [comment]
looks good

**Pull request merged**
